const fallbackProducts=[{name:'NovaCore',growth:14.8,forecast:9360,inventory:7420},{name:'Lumena',growth:9.6,forecast:7480,inventory:7050},{name:'Virelix',growth:4.2,forecast:6380,inventory:6700},{name:'Asteron',growth:-7.4,forecast:4910,inventory:6680},{name:'Kinetra',growth:18.1,forecast:5290,inventory:3910},{name:'Solvexa',growth:-12.6,forecast:2980,inventory:5120}];
const fallbackRegions=[{name:'South',revenue:4.15e6,share:30.5},{name:'West',revenue:3.62e6,share:26.6},{name:'North',revenue:3.11e6,share:22.9},{name:'East',revenue:2.72e6,share:20}];
const fallbackDemand=[34520,35480,36920,38640,37810,39270];
const knowledge=[
{id:'doc-001',title:'Q1 Commercial Performance Review',page:8,topic:'performance growth retention product availability',excerpt:'Prioritize measurable commercial outcomes, high-value customer retention, product availability and evidence-backed next-best actions.'},
{id:'doc-002',title:'Regional Growth Strategy',page:6,topic:'region performance growth conversion product mix',excerpt:'Regional recommendations should separate revenue concentration, product mix, customer behavior and execution signals before intervention.'},
{id:'doc-003',title:'Customer Segmentation Playbook',page:11,topic:'customer segment rfm retention recency frequency value',excerpt:'Customer actions should combine recency, frequency, monetary value and recent trajectory instead of relying on spend alone.'},
{id:'doc-004',title:'Demand Planning Brief',page:5,topic:'forecast demand inventory confidence supply',excerpt:'Demand decisions should combine forecast point estimates, confidence ranges and current inventory before changing supply.'},
{id:'doc-005',title:'Commercial Risk Review',page:9,topic:'risk anomaly customer product exposure',excerpt:'Prioritize risks by business impact, model probability and commercial value, with human review before material action.'}
];
const pct=n=>`${n>=0?'+':''}${Number(n||0).toFixed(1)}%`;
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));

function getOrigin(req){const host=req.headers['x-forwarded-host']||req.headers.host||process.env.VERCEL_URL;if(!host)return null;const proto=req.headers['x-forwarded-proto']||(String(host).includes('localhost')?'http':'https');return `${proto}://${host}`}

async function loadLiveData(req){try{const origin=getOrigin(req);if(!origin)return null;const response=await fetch(`${origin}/api/commercial-data`,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)return null;const payload=await response.json();return payload?.ok&&payload?.schema==='commercialiq'?payload:null}catch{return null}}

function buildContext(payload){if(!payload)return null;
 const forecastRows=[...(payload.forecasts||[])].sort((a,b)=>String(a.forecast_period).localeCompare(String(b.forecast_period)));
 const firstForecast=new Map();forecastRows.forEach(row=>{if(!firstForecast.has(row.product_id))firstForecast.set(row.product_id,Number(row.predicted_units)||0)});
 const products=(payload.products||[]).map(p=>({name:p.product_name||p.product_id,growth:Number(p.growth)||0,revenue:Number(p.revenue)||0,units:Number(p.units)||0,inventory:Number(p.inventory)||0,forecast:firstForecast.get(p.product_id)||0}));
 const regionEntries=Object.entries(payload.regions||{}),totalRegionRevenue=regionEntries.reduce((s,[,m])=>s+(Number(m.revenue)||0),0);
 const regions=regionEntries.map(([name,m])=>({name,revenue:Number(m.revenue)||0,units:Number(m.units)||0,share:totalRegionRevenue?((Number(m.revenue)||0)/totalRegionRevenue)*100:0})).sort((a,b)=>b.revenue-a.revenue);
 const forecastPeriods=new Map();forecastRows.forEach(row=>{const period=row.forecast_period;if(!period)return;forecastPeriods.set(period,(forecastPeriods.get(period)||0)+(Number(row.predicted_units)||0))});
 const demand=[...forecastPeriods.entries()].sort(([a],[b])=>String(a).localeCompare(String(b))).map(([period,units])=>({period,units:Math.round(units)}));
 const segmentMap=new Map();(payload.segments||[]).forEach(row=>{const name=row.segment_name||'Unassigned',s=segmentMap.get(name)||{name,count:0,value:0,recency:0,frequency:0};s.count++;s.value+=Number(row.monetary_value)||0;s.recency+=Number(row.recency_days)||0;s.frequency+=Number(row.frequency)||0;segmentMap.set(name,s)});
 const segments=[...segmentMap.values()].map(s=>({...s,avgRecency:s.count?s.recency/s.count:0,avgFrequency:s.count?s.frequency/s.count:0})).sort((a,b)=>b.value-a.value);
 const segmentByCustomer=new Map((payload.segments||[]).map(row=>[row.customer_id,row]));
 const risks=(payload.risks||[]).slice(0,10).map(row=>{const customer=segmentByCustomer.get(row.customer_id);const probability=Number(row.risk_probability)||0;return{customerId:row.customer_id,risk:Math.round((probability<=1?probability*100:probability)),segment:customer?.segment_name||'Unassigned',value:Number(customer?.monetary_value)||0,drivers:row.drivers||{}}});
 return{metrics:payload.metrics||{},products,regions,demand,segments,risks,documents:payload.documents||[]}}

function retrieve(question){const terms=question.toLowerCase().split(/\W+/).filter(t=>t.length>2);return knowledge.map(d=>({...d,score:terms.reduce((s,t)=>s+(`${d.title} ${d.topic} ${d.excerpt}`.toLowerCase().includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score).slice(0,2)}
function toolPlan(q){const s=q.toLowerCase();if(/forecast|demand|inventory|supply/.test(s))return['forecast_sales','get_product_performance','calculate_inventory_gap'];if(/customer|segment|retention|churn/.test(s))return['get_customer_segments','identify_at_risk_customers','rank_next_best_actions'];if(/region|east|south|west|north/.test(s))return['get_region_performance','get_product_performance','detect_sales_anomalies'];if(/risk|weak|declin|problem|anomal/.test(s))return['detect_sales_anomalies','identify_at_risk_customers','get_product_performance'];return['get_revenue_summary','get_product_performance','get_customer_segments']}

function deterministic(question,ctx){const q=question.toLowerCase();if(!ctx){const weak=[...fallbackProducts].sort((a,b)=>a.growth-b.growth),strong=[...fallbackProducts].sort((a,b)=>b.growth-a.growth);if(/forecast|demand|inventory|supply/.test(q))return `Portfolio demand is projected to rise from ${fallbackDemand[0].toLocaleString('en-IN')} units next period to ${fallbackDemand.at(-1).toLocaleString('en-IN')} units across the six-period horizon. Kinetra has the clearest supply pressure, while Solvexa has declining momentum and inventory above forecast demand. Recommendation: rebalance inventory toward growth products, but stay within forecast confidence bands.`;if(/risk|weak|declin|problem|anomal/.test(q))return `The clearest portfolio risks are ${weak[0].name} (${pct(weak[0].growth)}) and ${weak[1].name} (${pct(weak[1].growth)}). Protect availability for ${strong[0].name} while reducing excess exposure on declining products.`;return 'CommercialIQ is operating in resilient fallback mode. Core decision-support functions remain available while live data is temporarily unavailable.'}
 const products=[...ctx.products],weak=[...products].sort((a,b)=>a.growth-b.growth),strong=[...products].sort((a,b)=>b.growth-a.growth),topRegion=ctx.regions[0],topRisk=[...ctx.risks].sort((a,b)=>b.risk-a.risk)[0];
 if(/forecast|demand|inventory|supply/.test(q)){const first=ctx.demand[0],last=ctx.demand.at(-1),pressure=products.filter(p=>p.inventory>0&&p.forecast>p.inventory).sort((a,b)=>(b.forecast-b.inventory)-(a.forecast-a.inventory))[0];return `Portfolio demand is forecast at ${first?.units?.toLocaleString('en-IN')||'n/a'} units for the next period and ${last?.units?.toLocaleString('en-IN')||'n/a'} units by the end of the available horizon. ${pressure?`${pressure.name} has the largest modeled supply gap (${Math.round(pressure.forecast-pressure.inventory).toLocaleString('en-IN')} units).`:'No major modeled supply gap is visible.'} Use the confidence ranges in Forecasting before changing supply.`}
 if(/customer|segment|retention|churn/.test(q)){const attention=ctx.segments.filter(s=>/risk|inactive/i.test(s.name)),summary=attention.map(s=>`${s.name} (${s.count} customers)`).join(' and ')||`${ctx.segments[0]?.name||'the leading segment'} (${ctx.segments[0]?.count||0} customers)`;return `${summary} require the clearest customer attention. ${topRisk?`${topRisk.customerId} is the highest-ranked individual risk at ${topRisk.risk}% in the current model output.`:''} Prioritize high-value accounts using recency, frequency, monetary value and risk probability rather than broad discounting.`}
 if(/region|east|south|west|north/.test(q))return `${topRegion?.name||'The leading region'} currently contributes the largest revenue share at ${topRegion?topRegion.share.toFixed(1):'0'}%. Compare regional concentration with customer mix and product performance before changing allocation; revenue share alone should not be treated as causal evidence.`;
 if(/risk|weak|declin|problem|anomal/.test(q))return `The clearest live risks are ${weak[0]?.name||'the weakest product'} (${pct(weak[0]?.growth||0)} recent growth) and ${topRisk?`${topRisk.customerId} (${topRisk.risk}% predicted customer risk)`:'the highest-ranked customer-risk cohort'}. Recommended action: reduce exposure where product momentum is weakening, protect high-value customers, and validate interventions against forecast confidence and current inventory.`;
 if(/best|opportun|growth|strong/.test(q))return `The strongest live product opportunities are ${strong[0]?.name||'the leading product'} (${pct(strong[0]?.growth||0)}) and ${strong[1]?.name||'the second-ranked product'} (${pct(strong[1]?.growth||0)}). ${topRegion?`${topRegion.name} has the largest current regional revenue share (${topRegion.share.toFixed(1)}%).`:''} Protect availability for growth products and verify that added inventory converts into realized revenue.`;
 return `CommercialIQ currently tracks ${money(ctx.metrics.revenue)} in synthetic portfolio revenue, ${Number(ctx.metrics.units||0).toLocaleString('en-IN')} units and ${Number(ctx.metrics.customers||0).toLocaleString('en-IN')} active customer IDs. The portfolio is mixed: growth leaders should receive availability protection while weak products and high-risk accounts need targeted review.`}

async function gemini(question,tools,sources,base,ctx){const key=process.env.GEMINI_API_KEY;if(!key)return null;const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';const grounded=ctx?{metrics:ctx.metrics,products:ctx.products,regions:ctx.regions,demand:ctx.demand,segments:ctx.segments,risks:ctx.risks,tools,sources}:{products:fallbackProducts,regions:fallbackRegions,demand:fallbackDemand,tools,sources};const prompt=`You are CommercialIQ, a commercial analytics decision-support assistant. Answer only from the supplied synthetic portfolio data. Never invent metrics. Give a concise finding, evidence, and recommended action. Treat correlations as signals, not causation. Do not reveal hidden reasoning. DATA: ${JSON.stringify(grounded)} USER: ${question} DETERMINISTIC BASELINE: ${base}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.2,maxOutputTokens:450}})});if(!r.ok)return null;const data=await r.json();return data?.candidates?.[0]?.content?.parts?.map(p=>p.text).join('\n').trim()||null}

export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Use POST with { question }.'});const question=typeof req.body?.question==='string'?req.body.question.trim():'';if(!question)return res.status(400).json({error:'Question is required.'});if(question.length>800)return res.status(400).json({error:'Question is too long.'});const live=await loadLiveData(req),ctx=buildContext(live),tools=toolPlan(question),sources=retrieve(question),base=deterministic(question,ctx);let answer=base,mode=ctx?'deterministic-live':'deterministic-fallback';try{const generated=await gemini(question,tools,sources,base,ctx);if(generated){answer=generated;mode=ctx?'gemini-grounded-live':'gemini-grounded-fallback'}}catch{}return res.status(200).json({answer,tools,sources,confidence:mode.startsWith('gemini')?.93:ctx?.91:.86,mode,dataSource:ctx?'live':'fallback'})}
